config/routes.rb
Rails.application.routes.draw do
  
  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end
  resources :collections

  get 'add_block' => 'collections#block'
  get 'add_image' => 'collections#add_image'
  get 'update_config' => 'collections#update_config'

  root :to => 'collections#index'
  

end

app/models/session_storage.rb
class SessionStorage
  def self.store(session)
    shop = Shop.find_or_initialize_by(shopify_domain: session.url)
    shop.shopify_token = session.token
    shop.save!
    shop.id
  end

  def self.retrieve(id)
    return unless id
    shop = Shop.find(id)
    ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ShopifyApp::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :login_again_if_different_shop
  around_filter :shopify_session
  layout ShopifyApp.configuration.embedded_app? ? 'embedded_app' : 'application'
end

app/controllers/collections_controller.rb
class CollectionsController < AuthenticatedController
	require 'securerandom'
	
	def index
		@custom_collections = ShopifyAPI::CustomCollection.find(:all)
    	@smart_collections = ShopifyAPI::SmartCollection.find(:all)
	end
	def show
		@type = params[:type]
		if params[:type] == 'smart'
			@collection = ShopifyAPI::SmartCollection.find(params[:id])	
		elsif params[:type] == 'custom'
			@collection = ShopifyAPI::CustomCollection.find(params[:id])
		end
		@blocks = ShopifyAPI::Metafield.find(:all, :params =>{:resource => 'collections', :resource_id => @collection.id, :namespace => 'block'})
		@products = ShopifyAPI::Product.find(:all, :params => {:collection_id => @collection.id, :fields => ['title', 'images', 'id']})
		@config = ShopifyAPI::Metafield.find(:first, :params =>{:resource => 'collections', :resource_id => @collection.id, :namespace => 'config'})
		if @config.present?
			config_val = @config.value.split(';;')
			@background_color = config_val[0] 
			@text_color = config_val[1]
		end 
	end

	def destroy
		if params[:type] == 'smart'
			@collection = ShopifyAPI::SmartCollection.find(params[:collection])	
		elsif params[:type] == 'custom'
			@collection = ShopifyAPI::CustomCollection.find(params[:collection])
		end
		metafield = ShopifyAPI::Metafield.find(params[:id])
		metafield.destroy
		redirect_to collection_path(@collection, type: params[:type])
	end

	def block
		@block_type = params[:block_type]
		@collection = params[:collection]
		@type = params[:type]
		respond_to do |format|               
		   format.js
		 end 
	end
	def add_image
		if params[:type] == 'smart'
			@collection = ShopifyAPI::SmartCollection.find(params[:collection])	
		elsif params[:type] == 'custom'
			@collection = ShopifyAPI::CustomCollection.find(params[:collection])
		end
		@images = params[:images]
		@random_string = SecureRandom.hex(5)
		@collection.add_metafield(ShopifyAPI::Metafield.new(namespace: 'block', key: @random_string,  value: @images + ';;' + params[:block_type], value_type: "string"))
		redirect_to collection_path(@collection)
	end
	def update_config
		@data = params[:config_data]
		if params[:type] == 'smart'
			@collection = ShopifyAPI::SmartCollection.find(params[:collection])	
		elsif params[:type] == 'custom'
			@collection = ShopifyAPI::CustomCollection.find(params[:collection])
		end
		@collection.add_metafield(ShopifyAPI::Metafield.new(namespace:'config', key: @collection.id,  value: @data, value_type: "string"))
		redirect_to collection_path(@collection)
	end
end

app/controllers/home_controller.rb
class HomeController < AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, :params => {:limit => 10})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ShopifyApp::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_block_one_fields.html.erb
<section>	
	<div class="card">
		<div class="flex-container container--grey">
			<div class="two--thirds data-image"><i class="image icon-photos"></i></div>
			<div class="one--third">
				<div class="data-image"><i class="image icon-photos"></i></div>
				<div class="data-image"><i class="image icon-photos"></i></div>
			</div>
		</div>
		<button class="button add-block" data-blocktype="1">add block</button>
	</div>
</section>

app/views/collections/_block_three_fields.html.erb
<section>
	<div class="card">
		<div class="flex-container container--grey">
			<div class="half data-image"><i class="image icon-photos"></i></div>
			<div class="half data-image"><i class="image icon-photos"></i></div>
		</div>
		<button class="button add-block" data-blocktype="3">add block</button>
	</div>
</section>

app/views/collections/_block_two_fields.html.erb
<section>
	<div class="card">
		<div class="flex-container container--grey">
			<div class="third data-image"><i class="image icon-photos"></i></div>
			<div class="third data-image"><i class="image icon-photos"></i></div>
			<div class="third data-image"><i class="image icon-photos"></i></div>
		</div>
		<button class="button add-block" data-blocktype="2">add block</button>
	</div>
</section>

app/views/collections/block.js.erb
if(<%= @block_type%> == 1){
	$('#grid').append("<%= escape_javascript(render :partial => 'block_one_fields', :locals => {collection: @collection}) %>");
}else if(<%= @block_type%> == 2){
	$('#grid').append("<%= escape_javascript(render :partial => 'block_two_fields') %>");
}else if (<%= @block_type%> == 3){
	$('#grid').append("<%= escape_javascript(render :partial => 'block_three_fields') %>");
}

app/views/collections/index.html.erb
<section>
	<div class="card columns eight">	
		<h2>Collections</h2>
		<p>You can create custom photo grids for all your collections. Select one to get started.</p>

		<table>
		  <thead>
		    <tr>
		      <th colspan="5">Collection</th>
		    </tr>
		  </thead>
		  <tbody>
		  <% @smart_collections.each do |collection|%>
		      <tr>
		        <td><%= collection.title %></td>
		        <td></td>
		        <td></td>
		        <td></td>
		        <td><%= link_to 'edit', collection_path(collection, type: 'smart'), class: 'button secondary'%></td>
		      </tr>
		  <% end %> 
		  <% @custom_collections.each do |collection|%>
		      <tr>
		        <td><%= collection.title %></td>
		        <td></td>
		        <td></td>
		        <td></td>
		        <td><%= link_to 'edit', collection_path(collection, type: 'custom'), class: 'button secondary'%></td>
		      </tr>
		  <% end %>  
		  </tbody>
		</table>
	</div>
</section>


<section>
	<div class="card">
		<div class="flex-container">
			<div class="half"></div>
			<div class="half">
				<div class="quarter"></div>
				<div class="quarter"></div>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="card">
		<div class="flex-container">
			<div class="third"></div>
			<div class="third"></div>
			<div class="third"></div>
		</div>
	</div>
</section>
<section>
	<div class="card">
		<div class="flex-container">
			<div class="half"></div>
			<div class="half"></div>
		</div>
	</div>
</section>

app/views/collections/show.html.erb
<section>
	<div class="card columns eight">
		<h3><%= @collection.title%></h3>
		<% if @collection.metafields.present?%>
			<% @blocks.each do |m|%>
				<% @imgs = m.value.split(';;')%>
				<% block_type = @imgs.pop %>
				<% if block_type == '1' || block_type == '2' || block_type == '3' %>
					<% @img_1 = @imgs[0].split(':::')%>
					<% @img_2 = @imgs[1].split(':::')%>
					<% if block_type == '1' || block_type == '2'%>
						<% @img_3 = @imgs[2].split(':::')%>
					<% end %>
				<% end %>
					<% if block_type == '1' %>
						<div class="flex-container margin-bottom-20">
							<div class="two--thirds overlay-container">
								<img src="<%= @img_1[0]%>" alt="">
								<div class="overlay" style="background: <%= @background_color%>; color: <%= @text_color%>"><%= @img_1[1]%> | <%= @img_1[2]%></div>
							</div>
							<div class="one--third">
								<div class="overlay-container">
									<img src="<%= @img_2[0]%>" alt="">
									<div class="overlay"><%= @img_2[1]%> | <%= @img_2[2]%></div>
								</div>
								<div class="overlay-container">
									<img src="<%= @img_3[0]%>" alt="">
									<div class="overlay"><%= @img_3[1]%> | <%= @img_3[2]%></div>
								</div>
							</div>
						</div>
						<%= link_to 'delete', collection_path(m.id, collection: @collection, type: @type), method: :delete, class: 'button button--secondary button--destroy'%>
					<% elsif	block_type == '2'%>
						<div class="flex-container margin-bottom-20">
							<div class="third overlay-container">
								<img src="<%= @img_1[0]%>" alt="">
								<div class="overlay"><%= @img_1[1]%> | <%= @img_1[2]%></div>
							</div>
							<div class="third overlay-container">
								<img src="<%= @img_2[0]%>" alt="">
								<div class="overlay"><%= @img_2[1]%> | <%= @img_2[2]%></div>
							</div>
							<div class="third overlay-container">
								<img src="<%= @img_3[0]%>" alt="">
								<div class="overlay"><%= @img_3[1]%> | <%= @img_3[2]%></div>
							</div>
						</div>
						<%= link_to 'delete', collection_path(m.id, collection: @collection, type: @type), method: :delete, class: 'button button--secondary button--destroy'%>
					<% elsif block_type == '3'%>	
						<div class="flex-container margin-bottom-20">
							<div class="half overlay-container">
								<img src="<%= @img_1[0]%>" alt="">
								<div class="overlay"><%= @img_1[1]%> | <%= @img_1[2]%></div>
							</div>
							<div class="half overlay-container">
								<img src="<%= @img_2[0]%>" alt="">
								<div class="overlay"><%= @img_2[1]%> | <%= @img_2[2]%></div>
							</div>
						</div>
						<%= link_to 'delete', collection_path(m.id, collection: @collection, type: @type), method: :delete, class: 'button button--secondary button--destroy'%>
					<% end %>
			<% end %>
		<% end %>
		<p><%= @products.first.title%> | <%=@products.first.images.first.src%> | <%= @products.first.id%></p>
		<div id="grid">
			
		</div>
	</div>
	<div class="card columns four" id="config-panel">
		<p>Card</p>
		<%= link_to 'add block one', add_block_path(block_type: '1', collection: @collection, type: @type), :remote => true, class: 'button secondary' %>
		<%= link_to 'add block two', add_block_path(block_type: '2'), :remote => true, class: 'button secondary' %>
		<%= link_to 'add block three', add_block_path(block_type: '3'), :remote => true, class: 'button secondary' %>

		<h2>Color</h2>
		<form action="" id="config-form">
			<label for="background-color">Overlay Background</label>
			<input type="color" id="background-color" name="background-color" value="<%= @background_color%>">
			<label for="text-color">Overlay Text Color</label>
			<input type="color" id="text-color" name="text-color" value="<%= @text_color%>">
			<div id="cp2" class="input-group colorpicker-component">
			    <input type="text" value="#00AABB" class="form-control" />
			    <span class="input-group-addon"><i></i></span>
			</div>
			<label for="include-price">Include price on overlay</label>
			<input type="checkbox" id="include-price" name="include-price">
		</form>
	</div>
</section>

<div class="modal hidden" id="image-gallery">
	<div class="image-gallery flex-container">
		<% @products.each do |product|%>
			<% product.images.each do |image|%>
				<img src="<%= image.src %>" alt="product.title" data-producttitle="<%= product.title%>" data-productid="<%= product.id%>">
			<% end %>
		<% end %>
	</div>
</div>
<script>
	$('#cp2').colorpicker();
	$('body').on('click','.add-block', function(){
		var images = $(this).parent('.card').find('.data-image')
		var block_type = $(this).data('blocktype')
		var images_array = images.map(function(i, image){
			console.log(image, i)
			return $(image).data('image')
		}).toArray()

		images_string = images_array.join(';;')
		console.log(images_array, 'array')
		$.ajax({
	        url: '/add_image',
	        type: 'GET',
	        data: {
	          collection: <%= @collection.id%>, 
	          type: '<%= @type.to_s%>', 
	          block_type: block_type, 
	          images: images_string
	        },
	        dataType: 'script'
      	});
	})

	$('#config-panel').on('change', function(){
		var form_data = $('#config-form').serializeArray()
		console.log(form_data)
		var data = form_data.map(function(el, i){
			return el.value
		})
		data = data.join(';;')

		$.ajax({
	        url: '/update_config',
	        type: 'GET',
	        data: {
	          collection: <%= @collection.id%>, 
	          type: '<%= @type.to_s%>', 
	          config_data: data
	        },
	        dataType: 'script'
     });
	})
</script>

app/views/home/index.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Home",
      icon: "<%= asset_path('faveicon.png') %>"
    });
  });
</script>
<h3>Products</h3>
<table>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <a href='https://<%="#{@shop_session.url}/admin/products/#{product.id}"%>' target="_blank"> <%= product.id %> </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopifyImageGelleryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= insert_paloma_hook %>
</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shopify Embedded Example App</title>

  <script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
  <script type="text/javascript">
    ShopifyApp.init({
      apiKey: "<%= ShopifyApp.configuration.api_key %>",
      shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
      debug: <%= Rails.env.development? ? 'true' : 'false' %>
    });
  </script>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
  <%= insert_paloma_hook %>
</body>
</html>